"""create post table

Revision ID: ecf6960f907f
Revises: 
Create Date: 2026-02-18 19:19:44.599694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecf6960f907f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    # sa.Column('currency', sa.Enum('USD', 'INR', 'EUR', 'GBP', name='currency_enum'), nullable=False),
    # sa.Column('url', sa.Text(), nullable=True),
    # sa.Column('tags', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # op.create_table('posts',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('title', sa.String(), nullable=False),
    # sa.Column('content', sa.String(), nullable=True),
    # sa.Column('img_url', sa.Text(), nullable=True),
    # sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    # sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    # sa.Column('user_id', sa.Integer(), nullable=False),
    # sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_index(op.f('ix_posts_id'), 'posts', ['id'], unique=False)
    # op.create_table('post_likes',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('user_id', sa.Integer(), nullable=False),
    # sa.Column('post_id', sa.Integer(), nullable=False),
    # sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    # sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    # sa.PrimaryKeyConstraint('id'),
    # sa.UniqueConstraint('post_id', 'user_id', name='unique_post_like')
    # )
    # op.create_table('votes',
    # sa.Column('post_id', sa.Integer(), nullable=False),
    # sa.Column('user_id', sa.Integer(), nullable=False),
    # sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    # sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    # sa.PrimaryKeyConstraint('post_id', 'user_id')
    # )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('votes')
    # op.drop_table('post_likes')
    # op.drop_index(op.f('ix_posts_id'), table_name='posts')
    # op.drop_table('posts')
    op.drop_table('users')
    op.drop_table('products')
    # ### end Alembic commands ###
